export const customerMasterConfig = {
  sectionLabel: "Customer Master Overview",

  kpis: [
    {
      label: "Total Customers",
      valuePath: "kpis.totalCustomers.title",
      subPath: "kpis.totalCustomers.subtitle",
      footerPath: "kpis.totalCustomers.footer",
      iconName: "personFolder",
      accent: "c1",
      sparkPct: 100,
      badgePath: "kpis.totalCustomers.badge",
    },
    {
      label: "With Bank Account",
      valuePath: "kpis.withBankAccount.title",
      subPath: "kpis.withBankAccount.subtitle",
      footerPath: "kpis.withBankAccount.footer",
      iconName: "withBankAccount",
      accent: "c2",
      sparkPct: 65,
      badgePath: "kpis.withBankAccount.badge",
    },
    {
      label: "GSTIN Registered",
      valuePath: "kpis.gstinRegistered.title",
      subPath: "kpis.gstinRegistered.subtitle",
      footerPath: "kpis.gstinRegistered.footer",
      iconName: "document",
      accent: "c3",
      sparkPct: 77,
      badgePath: "kpis.gstinRegistered.badge",
    },
    {
      label: "States Covered",
      valuePath: "kpis.statesCovered.title",
      subPath: "kpis.statesCovered.subtitle",
      footerPath: "kpis.statesCovered.footer",
      iconName: "location",
      accent: "c4",
      sparkPct: 39,
      badgePath: "kpis.statesCovered.badge",
    },
  ],

  charts: [
    {
      section: "twoCol",
      type: "verticalBarWithLine",
      title: "Customers by State / Region",
      barSize: 46,
      subtitle: "GEOGRAPHIC DISTRIBUTION & SHARE %",
      dataPath: "customersByRegion",

      limitOptions: [5, 10, 15, 20],
      defaultLimit: 10,
      slantLabels: true,

      axis: {
        xLabel: "State / Region",
        yLeftLabel: "Count",
        yRightLabel: "Share %",
      },
    },
    {
      section: "twoCol",
      type: "donut",
      title: "TDS / WHT Category Breakdown",
      subtitle: "WITHHOLDING TAX TYPES",
      dataPath: "tdsBreakdown",
    },
    {
      section: "twoCol",
      type: "donut",
      title: "Bank Account Coverage",
      subtitle: "BANKING REGISTRATION STATUS",
      dataPath: "bankCoverage",
    },
    {
      section: "twoCol",
      type: "verticalBar",
      title: "Top Cities by Customer Count",
      subtitle: "CITY DISTRIBUTION",
      dataPath: "topCities",
      slantLabels: true,
      limitOptions: [5, 10, 15, 20],
      defaultLimit: 10,
    },
    {
      section: "twoCol",
      type: "verticalBar",
      title: "Bank Coverage by State",
      subtitle: "WITH BANK CUSTOMERS BY STATE",
      dataPath: "bankCoverageByState",
      slantLabels: true,
      limitOptions: [5, 10, 15, 20],
      defaultLimit: 10,
    },
    {
      section: "twoCol",
      type: "donut",
      title: "Reconciliation Account Split",
      subtitle: "RECON ACCOUNT TYPE DISTRIBUTION",
      dataPath: "reconciliationSplit",
    },
  ],
};