export const bankingConfig = {
  sectionLabel: "Banking Analysis",

  kpis: [
    {
      label: "With Bank Account",
      valuePath: "kpis.withBankAccount.title",
      subPath: "kpis.withBankAccount.subtitle",
      footerPath: "kpis.withBankAccount.footer",
      iconName: "withBankAccount",
      accent: "c1",
      sparkPct: 78,
      badgePath: "kpis.withBankAccount.badge",
    },
    {
      label: "Without Bank Account",
      valuePath: "kpis.withoutBankAccount.title",
      subPath: "kpis.withoutBankAccount.subtitle",
      footerPath: "kpis.withoutBankAccount.footer",
      iconName: "dashboardPanelIcon",
      accent: "c2",
      sparkPct: 22,
      badgePath: "kpis.withoutBankAccount.badge",
    },
    {
      label: "Unique Banks",
      valuePath: "kpis.uniqueBanks.title",
      subPath: "kpis.uniqueBanks.subtitle",
      footerPath: "kpis.uniqueBanks.footer",
      iconName: "chatBubbleIcon",
      accent: "c3",
      sparkPct: 70,
      badgePath: "kpis.uniqueBanks.badge",
    },
    {
      label: "Bank Coverage %",
      valuePath: "kpis.bankCoveragePct.title",
      subPath: "kpis.bankCoveragePct.subtitle",
      footerPath: "kpis.bankCoveragePct.footer",
      iconName: "personFolder",
      accent: "c4",
      sparkPct: 78,
      badgePath: "kpis.bankCoveragePct.badge",
    },
  ],

  charts: [
    {
      title: "Bank Coverage by Region",
      subtitle: "REGION-WISE VENDORS WITH BANK DETAILS",
      type: "verticalBar",
      dataPath: "bankCoverageByRegion",
      xKey: "name",
      barKey: "value",
      defaultLimit: 10,
      limitOptions: [5, 10, 15, 20],
      slantLabels: true,
      height: 330,
      barSize: 34,
    },
    {
      title: "Top Banks by Vendor Count",
      subtitle: "TOP BANK KEYS BY VENDOR COUNT",
      type: "verticalBar",
      dataPath: "topBanksByVendorCount",
      xKey: "name",
      barKey: "value",
      defaultLimit: 10,
      limitOptions: [5, 10, 15, 20],
      slantLabels: true,
      height: 330,
      barSize: 34,
    },
  ],

  table: {
    title: "Vendor Banking Register",
    subtitle: "FULL VENDOR BANKING RECORDS",
    dataPath: "table",
    columns: [
      { key: "bp_no", label: "BP No." },
      { key: "vendor_name", label: "Vendor Name" },
      { key: "bank_country", label: "Bank Country" },
      { key: "bank_id", label: "Bank ID" },
      { key: "bank_key", label: "Bank Key" },
      { key: "bank_account", label: "Bank Account" },
      { key: "account_name", label: "Account Name" },
      { key: "account_holder", label: "Account Holder" },
      { key: "bank_name", label: "Bank Name" },
      { key: "bank_branch", label: "Bank Branch" },
      { key: "status", label: "Status" },
    ],
  },
};