export const geographicConfig = {
  sectionLabel: "Geographic Analysis",

  kpis: [
    {
      label: "States Covered",
      valuePath: "kpis.statesCovered.title",
      subPath: "kpis.statesCovered.subtitle",
      footerPath: "kpis.statesCovered.footer",
      iconName: "location",
      accent: "c1",
      sparkPct: 93,
      badge: {
        label: "INDIA",
        bgColor: "#E3F2FD",
        textColor: "#1565C0",
      },
    },
    {
      label: "Top Region",
      valuePath: "kpis.topRegion.title",
      subPath: "kpis.topRegion.subtitle",
      footerPath: "kpis.topRegion.footer",
      iconName: "locationMapIcon",
      accent: "c2",
      sparkPct: 73,
      badge: {
        label: "TOP",
        bgColor: "#E8F5E9",
        textColor: "#2E7D32",
      },
    },
    {
      label: "Total Cities",
      valuePath: "kpis.totalCities.title",
      subPath: "kpis.totalCities.subtitle",
      footerPath: "kpis.totalCities.footer",
      iconName: "citiesIcon",
      accent: "c3",
      sparkPct: 80,
      badge: {
        label: "CITIES",
        bgColor: "#FFF3E0",
        textColor: "#FB8C00",
      },
    },
    {
      label: "Avg per State",
      valuePath: "kpis.avgPerState.title",
      subPath: "kpis.avgPerState.subtitle",
      footerPath: "kpis.avgPerState.footer",
      iconName: "calendarIcon",
      accent: "c4",
      sparkPct: 66,
      badge: {
        label: "AVG",
        bgColor: "#F3E5F5",
        textColor: "#7B1FA2",
      },
    },
  ],

  charts: [
    {
      title: "Vendor Count by State",
      subtitle: "STATE-WISE VENDOR DISTRIBUTION",
      type: "verticalBar",
      section: "full",
      dataPath: "vendorCountByState",
      xKey: "name",
      barKey: "customers",
      defaultLimit: 10,
      limitOptions: [5, 10, 15, 20],
      slantLabels: true,
      height: 340,
      barSize: 34,
    },
    {
      title: "Regional Share",
      subtitle: "REGIONAL SHARE BY VENDOR COUNT",
      type: "donut",
      section: "twoCol",
      dataPath: "regionalShare",
      nameKey: "name",
      valueKey: "value",
      defaultLimit: 10,
      limitOptions: [5, 10, 15, 20],
      height: 320,
    },
    {
      title: "Top Cities by Count",
      subtitle: "CITY-WISE VENDOR DISTRIBUTION",
      type: "verticalBar",
      section: "twoCol",
      dataPath: "topCitiesByCount",
      xKey: "name",
      barKey: "customers",
      defaultLimit: 10,
      limitOptions: [5, 10, 15, 20],
      slantLabels: true,
      height: 320,
      barSize: 30,
    },
  ],

  table: {
    title: "Geographic Vendor Register",
    subtitle: "CITY / STATE-WISE VENDOR PRESENCE",
    dataPath: "table",
    columns: [
      { key: "state_region", label: "State / Region" },
      { key: "city", label: "City" },
      { key: "customers", label: "Vendors" },
      { key: "with_bank", label: "With Bank" },
      { key: "gstin_registered", label: "GSTIN Registered" },
      { key: "share_pct", label: "Share %" },
    ],
  },
};