export const taxComplianceConfig = {
  sectionLabel: "Tax Compliance",

  kpis: [
    {
      label: "GSTIN Registered",
      valuePath: "kpis.gstinRegistered.title",
      subPath: "kpis.gstinRegistered.subtitle",
      footerPath: "kpis.gstinRegistered.footer",
      iconName: "document",
      accent: "c1",
      sparkPct: 10,
      badgePath: "kpis.gstinRegistered.badge",
    },
    {
      label: "PAN on File",
      valuePath: "kpis.panOnFile.title",
      subPath: "kpis.panOnFile.subtitle",
      footerPath: "kpis.panOnFile.footer",
      iconName: "tickmarkIcon",
      accent: "c2",
      sparkPct: 90,
      badgePath: "kpis.panOnFile.badge",
    },
    {
      label: "TDS Assigned",
      valuePath: "kpis.tdsAssigned.title",
      subPath: "kpis.tdsAssigned.subtitle",
      footerPath: "kpis.tdsAssigned.footer",
      iconName: "SecurityIcon",
      accent: "c3",
      sparkPct: 27,
      badgePath: "kpis.tdsAssigned.badge",
    },
    {
      label: "TDS Categories",
      valuePath: "kpis.tdsCategories.title",
      subPath: "kpis.tdsCategories.subtitle",
      footerPath: "kpis.tdsCategories.footer",
      iconName: "tdsAnalyticsIcon",
      accent: "c4",
      sparkPct: 70,
      badgePath: "kpis.tdsCategories.badge",
    },
  ],

  charts: [
    {
      title: "TDS Code Distribution",
      subtitle: "TDS / WITHHOLDING CODE BREAKDOWN",
      type: "verticalBar",
      section: "twoCol",
      dataPath: "tdsCodeDistribution",
      xKey: "name",
      barKey: "value",
      defaultLimit: 10,
      limitOptions: [5, 10, 15, 20],
      slantLabels: true,
      height: 330,
      barSize: 34,
    },
    {
      title: "GST Registration Status",
      subtitle: "GSTIN REGISTERED VS NOT REGISTERED",
      type: "donut",
      section: "twoCol",
      dataPath: "gstRegistrationStatus",
      nameKey: "name",
      valueKey: "value",
      height: 320,
    },
  ],

  duplicateSections: [
    {
      title: "Duplicate PAN Numbers",
      badgeVariant: "warn",
      dataPath: "duplicates.pan",
      groupKeyLabel: "PAN",
      columns: [
        { key: "bp_no", label: "BP No." },
        { key: "customer_name", label: "Vendor Name" },
        { key: "pan_no", label: "PAN" },
        { key: "gstin", label: "GSTIN" },
      ],
    },
    {
      title: "Duplicate GSTIN Numbers",
      badgeVariant: "risk",
      dataPath: "duplicates.gstin",
      groupKeyLabel: "GSTIN",
      columns: [
        { key: "bp_no", label: "BP No." },
        { key: "customer_name", label: "Vendor Name" },
        { key: "pan_no", label: "PAN" },
        { key: "gstin", label: "GSTIN" },
      ],
    },
  ],

  table: {
    title: "Vendor Tax Compliance Register",
    subtitle: "FULL VENDOR TAX / TDS RECORDS",
    dataPath: "table",
    columns: [
      { key: "bp_no", label: "BP No." },
      { key: "customer_name", label: "Vendor Name" },
      { key: "pan_no", label: "PAN" },
      { key: "gstin", label: "GSTIN" },
      { key: "tax_type", label: "Tax Type" },
      { key: "wht_code", label: "TDS Code" },
      { key: "wht_description", label: "TDS Description" },
      { key: "recon_account", label: "Recon Account" },
    ],
  },
};