export const vendorMasterPageConfig = {
  sectionLabel: "Vendor Master",

  kpis: [
    {
      label: "Total Duplicate BPs",
      valuePath: "kpis.totalDuplicateBps.title",
      subPath: "kpis.totalDuplicateBps.subtitle",
      footerPath: "kpis.totalDuplicateBps.footer",
      iconName: "duplicateIcon",
      accent: "c1",
      sparkPct: 100,
      badgePath: "kpis.totalDuplicateBps.badge",
    },
    {
      label: "Duplicate PAN Groups",
      valuePath: "kpis.duplicatePanGroups.title",
      subPath: "kpis.duplicatePanGroups.subtitle",
      footerPath: "kpis.duplicatePanGroups.footer",
      iconName: "document",
      accent: "c2",
      sparkPct: 60,
      badgePath: "kpis.duplicatePanGroups.badge",
    },
    {
      label: "Duplicate GSTIN Groups",
      valuePath: "kpis.duplicateGstinGroups.title",
      subPath: "kpis.duplicateGstinGroups.subtitle",
      footerPath: "kpis.duplicateGstinGroups.footer",
      iconName: "SecurityIcon",
      accent: "c3",
      sparkPct: 80,
      badgePath: "kpis.duplicateGstinGroups.badge",
    },
    {
      label: "Duplicate Bank Accounts",
      valuePath: "kpis.duplicateBankAccounts.title",
      subPath: "kpis.duplicateBankAccounts.subtitle",
      footerPath: "kpis.duplicateBankAccounts.footer",
      iconName: "withBankAccount",
      accent: "c4",
      sparkPct: 65,
      badgePath: "kpis.duplicateBankAccounts.badge",
    },
  ],

  table: {
    title: "Vendor Master Register",
    subtitle: "FULL VENDOR MASTER RECORDS",
    dataPath: "table",
    columns: [
      { key: "bp_no", label: "BP No." },
      { key: "bp_type", label: "BP Type" },
      { key: "vendor_acct", label: "Vendor Acct" },
      { key: "name", label: "Name" },
      { key: "city", label: "City" },
      { key: "region", label: "Region" },
      { key: "email", label: "Email" },
      { key: "mobile", label: "Mobile" },
      { key: "tds_code", label: "TDS Code" },
      { key: "tds_desc", label: "TDS Description" },
      { key: "withholding_subj", label: "Withholding Subject" },
      { key: "recipient", label: "Recipient" },
      { key: "pan_no", label: "PAN No." },
      { key: "gstin", label: "GSTIN" },
      { key: "bank", label: "Bank" },
      { key: "bank_name", label: "Bank Name" },
      { key: "bank_account", label: "Bank Account" },
      { key: "recon_acct", label: "Recon Acct" },
      { key: "role_type", label: "Role Type" },
      { key: "role_code", label: "Role Code" },
      { key: "msme", label: "MSME" },
      { key: "msme_no", label: "MSME No." },
    ],
  },

  duplicateSections: [
    {
      title: "Duplicate BP Names",
      badgeVariant: "warn",
      dataPath: "duplicates.names",
      groupKeyLabel: "BP Name",
      columns: [
        { key: "bp_no", label: "BP No." },
        { key: "vendor_name", label: "Vendor Name" },
        { key: "city", label: "City" },
        { key: "pan_no", label: "PAN" },
      ],
    },
    {
      title: "Duplicate PAN Numbers",
      badgeVariant: "warn",
      dataPath: "duplicates.pan",
      groupKeyLabel: "PAN",
      columns: [
        { key: "bp_no", label: "BP No." },
        { key: "vendor_name", label: "Vendor Name" },
        { key: "city", label: "City" },
      ],
    },
    {
      title: "Duplicate GSTIN Numbers",
      badgeVariant: "risk",
      dataPath: "duplicates.gstin",
      groupKeyLabel: "GSTIN",
      columns: [
        { key: "bp_no", label: "BP No." },
        { key: "vendor_name", label: "Vendor Name" },
        { key: "city", label: "City" },
      ],
    },
    {
      title: "Duplicate Bank Accounts",
      badgeVariant: "risk",
      dataPath: "duplicates.bankAccounts",
      groupKeyLabel: "Bank Account",
      columns: [
        { key: "bp_no", label: "BP No." },
        { key: "vendor_name", label: "Vendor Name" },
        { key: "city", label: "City" },
        { key: "bank", label: "Bank" },
      ],
    },
  ],
};