export const vendorMasterOverviewConfig = {
  sectionLabel: "Vendor Master Overview",

  kpis: [
    {
      label: "Total Vendors",
      valuePath: "kpis.totalVendors.title",
      subPath: "kpis.totalVendors.subtitle",
      footerPath: "kpis.totalVendors.footer",
      iconName: "rectangularPanelIcon",
      accent: "c1",
      sparkPct: 100,
      badgePath: "kpis.totalVendors.badge",
    },
    {
      label: "With Bank Account",
      valuePath: "kpis.withBankAccount.title",
      subPath: "kpis.withBankAccount.subtitle",
      footerPath: "kpis.withBankAccount.footer",
      iconName: "withBankAccount",
      accent: "c2",
      sparkPct: 78,
      badgePath: "kpis.withBankAccount.badge",
    },
    {
      label: "GSTIN Registered",
      valuePath: "kpis.gstinRegistered.title",
      subPath: "kpis.gstinRegistered.subtitle",
      footerPath: "kpis.gstinRegistered.footer",
      iconName: "document",
      accent: "c3",
      sparkPct: 10,
      badgePath: "kpis.gstinRegistered.badge",
    },
    {
      label: "States Covered",
      valuePath: "kpis.statesCovered.title",
      subPath: "kpis.statesCovered.subtitle",
      footerPath: "kpis.statesCovered.footer",
      iconName: "location",
      accent: "c4",
      sparkPct: 70,
      badgePath: "kpis.statesCovered.badge",
    },
  ],

  charts: [
    {
      title: "Vendors by State / Region",
      subtitle: "TOP STATES BY VENDOR COUNT",
      type: "verticalBarWithLine",
      dataPath: "vendorsByRegion",
      xKey: "name",
      barKey: "opening",
      lineKey: "eir",
      barName: "Vendors",
      lineName: "Share %",
      defaultLimit: 10,
      limitOptions: [5, 10, 15, 20],
      slantLabels: true,
      height: 330,
      barSize: 34,
    },

    {
      title: "TDS Category Breakdown",
      subtitle: "VENDOR TDS CLASSIFICATION",
      type: "donut",
      dataPath: "tdsBreakdown",
      nameKey: "name",
      valueKey: "value",
      height: 320,
    },

    {
      title: "Bank Account Coverage",
      subtitle: "VENDORS WITH / WITHOUT BANK DETAILS",
      type: "donut",
      dataPath: "bankCoverage",
      nameKey: "name",
      valueKey: "value",
      height: 320,
    },

    {
      title: "Top Cities by Vendor Count",
      subtitle: "CITY-WISE VENDOR DISTRIBUTION",
      type: "verticalBar",
      dataPath: "topCities",
      xKey: "name",
      barKey: "value",
      defaultLimit: 10,
      limitOptions: [5, 10, 15, 20],
      slantLabels: true,
      height: 330,
      barSize: 30,
    },

    {
      title: "Bank Coverage by State",
      subtitle: "WITH BANK VS NO BANK BY STATE",
      type: "stackedBar",
      dataPath: "bankCoverageByState",
      xKey: "name",
      series: [
        { key: "withBank", name: "With Bank", color: "#2f7ed8" },
        { key: "noBank", name: "No Bank", color: "#b8dcf6" },
      ],
      defaultLimit: 10,
      limitOptions: [5, 10, 15, 20],
      slantLabels: true,
      height: 420,
      barSize: 34,
    },

    {
      title: "Reconciliation Account Split",
      subtitle: "VENDOR RECON ACCOUNT DISTRIBUTION",
      type: "donut",
      dataPath: "reconciliationSplit",
      nameKey: "name",
      valueKey: "value",
      height: 320,
    },
  ],
};
