export const glOverviewConfig = {
  sectionLabel: "GL Master Overview",

  kpis: [
    {
      label: "Total GL Accounts",
      valuePath: "kpis.totalGlAccounts.title",
      subPath: "kpis.totalGlAccounts.subtitle",
      footerPath: "kpis.totalGlAccounts.footer",
      iconName: "accountsIcon",
      accent: "c1",
      sparkPct: 100,
      badgePath: "kpis.totalGlAccounts.badge",
    },
    {
      label: "Balance Sheet Accounts",
      valuePath: "kpis.balanceSheetAccounts.title",
      subPath: "kpis.balanceSheetAccounts.subtitle",
      footerPath: "kpis.balanceSheetAccounts.footer",
      iconName: "paper",
      accent: "c2",
      sparkPct: 56,
      badgePath: "kpis.balanceSheetAccounts.badge",
    },
    {
      label: "P&L Accounts",
      valuePath: "kpis.plAccounts.title",
      subPath: "kpis.plAccounts.subtitle",
      footerPath: "kpis.plAccounts.footer",
      iconName: "trending",
      accent: "c3",
      sparkPct: 44,
      badgePath: "kpis.plAccounts.badge",
    },
    {
      label: "Blocked Accounts",
      valuePath: "kpis.blockedAccounts.title",
      subPath: "kpis.blockedAccounts.subtitle",
      footerPath: "kpis.blockedAccounts.footer",
      iconName: "tickmarkIcon",
      accent: "c4",
      sparkPct: 5,
      badgePath: "kpis.blockedAccounts.badge",
    },
  ],

  charts: [
    {
      title: "Account Type Split",
      subtitle: "BALANCE SHEET VS P&L ACCOUNTS",
      type: "donut",
      dataPath: "accountTypeSplit",
      nameKey: "name",
      valueKey: "value",
      height: 320,
      colors: ["#1565C0", "#90CAF9"],
    },
    {
      title: "Accounts by Range",
      subtitle: "GL ACCOUNT RANGE DISTRIBUTION",
      type: "verticalBar",
      dataPath: "accountsByRange",
      xKey: "name",
      barKey: "value",
      slantLabels: false,
      height: 330,
      barSize: 42,
    },
  ],

  table: {
    title: "GL Account Range Summary",
    subtitle: "ACCOUNT TYPE AND BLOCKED STATUS BY RANGE",
    dataPath: "table",
    columns: [
      { key: "range", label: "Range" },
      { key: "category", label: "Category" },
      { key: "total", label: "Total" },
      { key: "bs", label: "B/S" },
      { key: "pl", label: "P&L" },
      { key: "blocked", label: "Blocked" },
      { key: "percent_total", label: "% Total" },
    ],
  },
};